config/routes.rb
Rails.application.routes.draw do
  resources :vacancies do
    get 'page/:page', :action => :index, :on => :collection
    put 'approve', :on => :member
  end
  resources :pages, :only => :show
  root :to => 'vacancies#index'
end

app/models/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  def authorize!(action, vacancy)
    case action
    when :read
      return vacancy.approved? || admin?(vacancy)
    when :edit, :update
      return (vacancy.approved? && owner?(vacancy)) || admin?(vacancy)
    when :destroy, :approve
      return admin?(vacancy)
    else
      raise StandardError, "Unknown action #{action.inspect}"
    end
  end

end

app/models/page.rb
require "html_generator"

class Page
  attr_reader :id

  def initialize(id = nil)
    @id = id
  end

  def self.find_by_id(id)
    return self.exists?(id) ? self.new(id) : nil
  end

  def self.exists?(id)
    self.ids.include?(id.to_s)
  end

  def self.ids
    ["about", "terms", "contacts"]
  end

  def persisted?
    false
  end

  def title
    Page.get_field(self.id, :title)
  end

  def body_markdown
    Page.get_field(self.id, :body)
  end

  def body_html
    HtmlGenerator.render(self.body_markdown)
  end

  private

  def self.i18n_key_for_field(id, field)
    "pages.show.#{id}.#{field}"
  end

  def self.get_field(id, field)
    I18n.translate i18n_key_for_field(id, field)
  end
end

app/models/vacancy.rb
require "token_generator"
require "html_generator"

class Vacancy < ActiveRecord::Base
  validates :title, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :email, :presence => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :unless => Proc.new { |vacancy| vacancy.email.blank? } }
  validates :expire_at, :presence => true

  before_create do |vacancy|
    vacancy.owner_token = TokenGenerator.generate_token
    vacancy.admin_token = TokenGenerator.generate_token
  end

  before_save do |vacancy|
    vacancy.excerpt_html     = HtmlGenerator.render extract_excerpt(vacancy.description)
    vacancy.description_html = HtmlGenerator.render vacancy.description
  end

  scope :approved, lambda { where("approved_at IS NOT NULL") }
  scope :not_approved, lambda { where({ :approved_at => nil }) }
  scope :not_outdated, lambda { |date| where("expire_at >= ?", date) }
  scope :descent_order, lambda { order("id DESC") }
  scope :available, lambda { approved.not_outdated(Date.current).descent_order }

  def approved?
    self.approved_at.present?
  end

  def approve!
    self.approved_at = Time.now and self.save!
  end

  def expired?
    self.expire_at.past?
  end

  protected

  # Take the first three parts of text
  def extract_excerpt(text, divider = "\r\n\r\n")
    text.lines(divider).to_a.each(&:strip!).reject(&:blank?).take(3).join(divider)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :assign_page

  respond_to :html

  def show
    if @page.present?
      respond_with(@page)
    else
      render(:file => "public/404", :layout => false, :status => :not_found)
    end
  end

  private

  def assign_page
    @page = Page.find_by_id(params[:id])
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_filter :assign_vacancy, :except => [:index, :new, :create]
  before_filter :store_token, :except => [:index, :new, :create]

  respond_to :html
  respond_to :xml, :only => :index

  include Authentication

  def index
    @vacancies = Vacancy.available.page(params[:page]).per(6)
    respond_with(@vacancies)
  end

  def new
    respond_with(@vacancy = Vacancy.new)
  end

  def create
    @vacancy = Vacancy.new(parameters)

    if @vacancy.save
      VacancyMailer.creation_notice(@vacancy).deliver
      flash[:success] = t("vacancies.create.success")
    end

    respond_with(@vacancy, :location => @vacancy.persisted? ?  root_url : nil)
  end

  def show
    if authorize!(:read, @vacancy)
      respond_with(@vacancy)
    else
      render(:file => 'public/404', :layout => false, :status => :not_found)
    end
  end

  def edit
    if authorize!(:edit, @vacancy)
      respond_with(@vacancy)
    else
      render(:file => 'public/404', :layout => false, :status => :not_found)
    end
  end

  def update
    if authorize!(:update, @vacancy)
      @vacancy.update_attributes(parameters) and flash[:success] = t("vacancies.update.success")
      respond_with(@vacancy)
    else
      render(:file => 'public/404', :layout => false, :status => :not_found)
    end
  end

  def destroy
    if authorize!(:destroy, @vacancy)
      @vacancy.destroy and flash[:success] = t("vacancies.destroy.success")
      respond_with(@vacancy, :location => root_url)
    else
      render(:file => 'public/404', :layout => false, :status => :not_found)
    end
  end

  def approve
    if authorize!(:approve, @vacancy)
      @vacancy.approve! and flash[:success] = t("vacancies.approve.success")
      VacancyMailer.approval_notice(@vacancy).deliver
      respond_with(@vacancy)
    else
      render(:file => 'public/404', :layout => false, :status => :not_found)
    end
  end

  private

  def parameters
    params.require(:vacancy).permit(
      :title, :description, :location, :company, :url, :name, :email,
      :phone, :expire_at
    )
  end

  def assign_vacancy
    @vacancy = Vacancy.find_by_id!(params[:id])
  end

  def owner?(vacancy)
    tokens.include?(vacancy.owner_token)
  end
  helper_method :owner?

  def admin?(vacancy)
    tokens.include?(vacancy.admin_token)
  end
  helper_method :admin?

  def token
    params[:token]
  end

  def tokens
    session[:tokens] || []
  end

  def store_token
    session[:tokens] = tokens.push(token).uniq if token.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
  def company_location_tag(vacancy)
    [vacancy.company, vacancy.location].reject{ |i| i.blank? }.join(" - ")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="description" content="<%= t(".meta_description") %>" />
  <meta name="keywords" content="<%= t(".meta_keywords") %>" />
  <title><%= yield(:meta_title) %></title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag :rss,
                              "http://feeds.feedburner.com/rubyjobsru",
                              { :title => t("layouts.application.meta_title") } %>
  <%= favicon_link_tag %>
</head>
<body>
  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert <%= key %> fade in">
      <a class="close" href="#" class="close" data-dismiss="alert">×</a>
      <p><%= value %></p>
    </div>
    <% end %>
    <div class="row content-section">
      <div class="span2 sidebar">
        <div class="logo">
          <%= link_to_if !current_page?(root_url),
                         image_tag("rubyjobs-logo.png",
                                   :size => "76x67",
                                   :alt => t(".meta_title")),
                         root_url %>
        </div>
        <div class="tips">
          <%= yield(:sidebar) %>
        </div>
        <div class="subscriptions">
          <h5><%= t("layouts.application.subscriptions") %></h5>
          <p>
            <a href="https://www.twitter.com/rubyjobsru">
              <span class="label label-info">Twitter</span>
            </a>
            <a href="http://feeds.feedburner.com/rubyjobsru">
              <span class="label label-warning">RSS</span>
            </a>
          </p>
        </div>
      </div>
      <div class="span8 offset2">
        <%= yield %>
      </div>
    </div>
    <% if current_page?(root_url) %>
    <hr />
    <div class="row content-section">
      <div class="span2 sidebar">
        <h1>Интересные события и проекты</h1>
      </div>
      <div class="span8 offset2">
        <div class="row">
          <div class="span4">
            <div class="event-logo">
              <%= link_to image_tag('gohiring200x48.png', :size => '200x48'),
                          'http://www.gohiring.com/?utm_source=rubyjobs.ru' %>
            </div>
            <p>
              <strong>GoHiring Talent Marketing API</strong>&nbsp;&mdash; это мощный инструмент, который безпроблемно интегрируется с любой E-Recruiting системой.
            </p>
            <p><%= link_to 'http://www.gohiring.com', 'http://www.gohiring.com/?utm_source=rubyjobs.ru' %></p>
          </div>
          <div class="span4">
            <div class="event-logo">
              <%= link_to image_tag("rubyflow135x80.png", :size => "135x80"),
                          "http://rubyflow.ru/?utm_source=rubyjobs.ru" %>
            </div>
            <p>Коллективный блог сообщества разработчиков.</p>
            <p>
              Более 1 400 статей на тему Ruby, Rails, Sinatra и других
              известных и не очень библиотек. Советы, обзоры и примеры кода.
            </p>
            <p>
              Формат коллективного блога позволяет каждому опубликовать
              статью. Без регистрации :)
            </p>
            <p><%= link_to 'http://rubyflow.ru', 'http://rubyflow.ru/?utm_source=rubyjobs.ru' %></p>
          </div>
        </div>
        <div class="row">
          <div class="span4">
            <div class="event-logo">
              <%= link_to image_tag('https://s3.eu-central-1.amazonaws.com/rubyflow-assets/company-mood.png', :height => 65, :width => 200),
                          'https://www.company-mood.com/?utm_source=rubyjobs.ru' %>
            </div>
            <p>
              CompanyMood - это онлайн-сервис, еженедельно измеряющий настроение сотрудников вашей компании.
            </p>
            <p>
              Он помогает вам принимать решения относительно HR-мероприятий, основываясь на информации полученной от самих сотрудников.
            </p>
            <p><%= link_to 'https://www.company-mood.com', 'https://www.company-mood.com/?utm_source=rubyjobs.ru' %></p>
          </div>
          <div class="span4">
            <div class="event-logo">
              <%= link_to image_tag('https://dl.dropboxusercontent.com/u/2628617/devconf120x28.png', :height => 28, :width => 120),
                          'http://devconf.ru/?utm_source=rubyjobs.ru' %>
            </div>
            <p>
              19-20 июня 2015 в Москве пройдет DevConf&nbsp;&mdash; профессиональная конференция, посвященная ведущим технологиям программирования и веб-разработки. В рамках мероприятия пройдут 7 конференций и ряд уникальных мастер-классов.
            </p>
            <p><%= link_to 'http://devconf.ru', 'http://devconf.ru/?utm_source=rubyjobs.ru' %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <footer class="row footer">
      <div class="span2">
        <p>
          &copy;&nbsp;2008&mdash;2015<br />
          <%= link_to "Alex Sulim", "http://sul.im" %>
        </p>
      </div>
      <div class="span4 offset2">
        <%= link_to image_tag('digitalocean-badge-gray.png', :size => '140x39'), 'http://www.digitalocean.com?utm_source=rubyjobs.ru' %>
      </div>
      <nav class="span4">
        <ul class="pull-right">
          <li><%= link_to t(".pages.about"), page_url(:about) %></li>
          <li><%= link_to t(".pages.terms"), page_url(:terms) %></li>
          <li><%= link_to t(".pages.contacts"), page_url(:contacts) %></li>
        </ul>
      </nav>
    </footer>
  </div>

  <%= javascript_include_tag "application" %>
  <%= yield(:js) %>
  <% if Rails.env.production? %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-391915-13']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>
  <% end %>
</body>
</html>

app/views/layouts/vacancy_mailer.text.erb
<%= yield %>

<%= t(".signature") %>

app/views/pages/show.html.erb
<% content_for :meta_title, t(".meta_title", :title => @page.title) %>
<article>
  <div class="page-header">
    <h1><%= @page.title %></h1>
  </div>
  <%= @page.body_html.html_safe %>
</article>

app/views/vacancies/_form.html.erb
<fieldset>
  <legend><%= t(".description") %></legend>
  <div class="control-group <%= "error" if form.object.errors.include?(:title) %>">
    <%= form.label :title,
                   "<strong>#{t("activerecord.attributes.vacancy.title")}</strong>".html_safe,
                   class: 'control-label' %>
    <div class="controls">
      <%= form.text_field :title,
                          class: 'span6',
                          autofocus: true,
                          placeholder: t(".placeholders.title") %>
      <% for error in form.object.errors.get(:title) %>
        <%= content_tag(:span, error, class: "help-block") %>
      <% end %>
    </div>
  </div>
  <div class="control-group <%= "error" if form.object.errors.include?(:description) %>">
    <%= form.label :description,
                   "<strong>#{t("activerecord.attributes.vacancy.description")}</strong>".html_safe,
                   class: 'control-label' %>
    <div class="controls">
      <%= form.text_area :description,
                      rows: 20,
                      class: 'span6',
                      placeholder: t(".placeholders.description") %>
      <% for error in form.object.errors.get(:description) %>
        <%= content_tag(:span, error, class: "help-block") %>
      <% end %>
    </div>
  </div>
  <div class="control-group <%= "error" if form.object.errors.include?(:location) %>">
    <%= form.label :location,
                   "<strong>#{t("activerecord.attributes.vacancy.location")}</strong>".html_safe,
                   class: 'control-label' %>
    <div class="controls">
      <%= form.text_field :location,
                          class: 'span6',
                          placeholder: t(".placeholders.location") %>
      <% for error in form.object.errors.get(:location) %>
        <%= content_tag(:span, error, class: "help-block") %>
      <% end %>
    </div>
  </div>
  <div class="control-group <%= "error" if form.object.errors.include?(:expire_at) %>">
    <%= form.label :expire_at,
                   "<strong>#{t("activerecord.attributes.vacancy.expire_at")}</strong>".html_safe,
                   class: 'control-label' %>
    <div class="controls">
      <label class="radio">
        <%= form.radio_button :expire_at, (form.object.persisted? ? form.object.created_at.to_date : Date.current) + 1.week %>
        <span><%= t(".notes.expire_at_one_week") %><span class="help-inline">&mdash; <%= t(".notes.valid_until", :date => l((form.object.persisted? ? form.object.created_at.to_date : Date.current) + 1.week)) %></span></span>
      </label>
      <label class="radio">
        <%= form.radio_button :expire_at, (form.object.persisted? ? form.object.created_at.to_date : Date.current) + 2.weeks %>
        <span><%= t(".notes.expire_at_two_weeks") %><span class="help-inline">&mdash; <%= t(".notes.valid_until", :date => l((form.object.persisted? ? form.object.created_at.to_date : Date.current) + 2.weeks)) %></span></span>
      </label>
      <label class="radio">
        <%= form.radio_button :expire_at, (form.object.persisted? ? form.object.created_at.to_date : Date.current) + 1.month %>
        <span><%= t(".notes.expire_at_one_month") %><span class="help-inline">&mdash; <%= t(".notes.valid_until", :date => l((form.object.persisted? ? form.object.created_at.to_date : Date.current) + 1.month)) %></span></span>
      </label>
      <% for error in form.object.errors.get(:expire_at) %>
        <%= content_tag(:span, error, :class => "help-block") %>
      <% end %>
     </div>
  </div>
</fieldset>
<fieldset>
  <legend><%= t(".legends.contacts") %></legend>
  <div class="control-group <%= "error" if form.object.errors.include?(:email) %>">
    <%= form.label :email,
                   "<strong>#{t("activerecord.attributes.vacancy.email")}</strong>".html_safe,
                   class: 'control-label' %>
    <div class="controls">
      <%= form.email_field :email, class: 'span4' %>
      <% for error in form.object.errors.get(:email) %>
        <%= content_tag(:span, error, class: "help-block") %>
      <% end %>
     </div>
  </div>
  <div class="control-group">
    <%= form.label :company, class: 'control-label' %>
    <div class="controls"><%= form.text_field :company, class: 'span4' %></div>
  </div>
  <div class="control-group">
    <%= form.label :url, class: 'control-label' %>
    <div class="controls"><%= form.url_field :url, class: 'span4' %></div>
  </div>
  <div class="control-group">
    <%= form.label :phone, class: 'control-label' %>
    <div class="controls"><%= form.telephone_field :phone, class: 'span4' %></div>
  </div>
  <div class="control-group">
    <%= form.label :name, class: 'control-label' %>
    <div class="controls"><%= form.text_field :name, class: 'span4' %></div>
  </div>
</fieldset>
<div class="form-actions">
  <% if form.object.persisted? %>
    <%= form.submit t(".update"), class: "btn btn-success" %>
    <%= link_to t(".cancel"), vacancy_url(form.object), class: "btn" %>
  <% else %>
    <p><%= t(".notes.terms.text", link: link_to(t(".notes.terms.link"), page_url(:terms))).html_safe %></p>
    <%= form.submit t(".create"), class: "btn btn-success" %>
    <%= link_to t(".cancel"), root_url, class: "btn" %>
  <% end %>
</div>

app/views/vacancies/edit.html.erb
<% content_for :meta_title, t(".meta_title") %>

<div>
  <%= form_for(@vacancy, html: { class: 'form-horizontal' }) { |f| render f } %>
</div>

app/views/vacancies/index.html.erb
<% content_for :meta_title, t(".meta_title") %>
<% content_for :sidebar do %>
  <h1><%= t(".sidebar.title") %></h1>
  <p><%= t(".sidebar.description") %></p>
  <p><%= link_to t(".add"), new_vacancy_url, :class => "btn btn-primary btn-large" %></p>
<% end %>

<% @vacancies.in_groups_of(2, false) do |group| %>
<div class="row">
  <% for vacancy in group %>
  <article class="span4">
    <h1><%= link_to vacancy.title, vacancy %></h1>
    <h3 class="muted company">
      <%= company_location_tag(vacancy) %><br/>
      <small><%== t('.expired_at', expired_at: l(vacancy.expire_at)) %></small>
    </h3>
    <%= vacancy.excerpt_html.html_safe %>
  </article>
  <% end %>
</div>
<% end %>

<%= paginate @vacancies %>

app/views/vacancies/new.html.erb
<% content_for :meta_title, t(".meta_title") %>
<% content_for :sidebar do %>
  <h1><%= t(".sidebar.title") %></h1>
  <p><%= t(".sidebar.description") %></p>
<% end %>

<div>
  <%= form_for(@vacancy, html: { class: 'form-horizontal' }) { |f| render f } %>
</div>

app/views/vacancies/show.html.erb
<%# content_for :sidebar %>
<% content_for :meta_title, t(".meta_title", :vacancy => @vacancy.title) %>
<% content_for :js do %>
  <!-- Facebook -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=293040454063703";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <!-- /Facebook -->
  <!-- G+ -->
  <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
  <!-- /G+ -->
<% end %>

<article>
  <div class="page-header">
    <h1><%= @vacancy.title %></h1>
    <h3 class="muted company">
      <%= company_location_tag(@vacancy) %><br/>
      <small><%== t('.expired_at', expired_at: l(@vacancy.expire_at)) %></small>
    </h3>
  </div>
  <%= @vacancy.description_html.html_safe %>
  <div class="row">
    <div class="span3">
      <address>
        <strong><%= t(".company") %></strong><br />
        <%= @vacancy.company %><br />
        <% unless @vacancy.url.blank? %>
          <%= link_to @vacancy.url, @vacancy.url %><br />
        <% end %>
        <% unless @vacancy.phone.blank? %>
          <%= t(".phone") %>: <%= @vacancy.phone %>
        <% end %>
      </address>
    </div>
    <div class="span3">
      <address>
        <strong><%= t(".contacts") %></strong><br />
        <% unless @vacancy.name.blank? %>
          <%= @vacancy.name %><br />
        <% end %>
        <%= mail_to @vacancy.email, nil, :encode => "hex", :replace_at => "[at]" %>
      </address>
    </div>
     <div class="span2">
      <strong><%= t(".share_links") %></strong><br />
      <ul class="share-buttons">
        <li>
          <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= vacancy_url(@vacancy) %>" data-text="<%= @vacancy.title %>" data-count="none" data-via="rubyjobsru">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
        </li>
        <li>
          <div class="g-plusone" data-size="medium" data-annotation="none"></div>
        </li>
        <li>
          <div style="display:inline-block;vertical-align:bottom;" class="fb-like" data-href="<%= vacancy_url(@vacancy) %>" data-send="false" data-layout="button_count" data-width="" data-show-faces="false" data-action="like"></div>
        </li>
      </ul>
     </div>
   </div>
  <% if admin?(@vacancy) %>
    <div class="form-actions">
      <%= button_to(t(".publish"), approve_vacancy_url(@vacancy), :method => "put", :class => "btn btn-success") unless @vacancy.approved? %>
      <%= link_to t(".edit"), edit_vacancy_url(@vacancy), :class => "btn" %>
      <%= button_to t(".destroy.button"), vacancy_url(@vacancy), :method => "delete", :confirm => t(".destroy.confirmation"), :class => "btn btn-danger" %>
    </div>
  <% elsif owner?(@vacancy) %>
    <div class="form-actions">
      <%= link_to t(".edit"), edit_vacancy_url(@vacancy), :class => "btn" %>
    </div>
  <% end %>
  <%= content_tag(:div,
                  t(".expiration_notice", :expire_at => l(@vacancy.expire_at)),
                  :class => "alert alert-block") if @vacancy.expired? %>
</article>